### ISSUE TITLE
error: github.com\hajimehoshi\oto\context.go:69:12: undefined: newDriver

### ISSUE THREAD

**Issue by zx0721** [hajimehoshi/oto#102]
github.com\hajimehoshi\oto\context.go:69:12: undefined: newDriver

**Comment by zx0721** [comment]
go version go1.14 windows/amd64

**Comment by hajimehoshi** [comment]
Hi, please give me more details. Thanks

**Comment by zx0721** [comment]
**my project build error message:**
github.com\hajimehoshi\oto\context.go:69:12: undefined: newDriver
**code:**
![image](https://user-images.githubusercontent.com/6317240/77243882-0d9d1700-6c4a-11ea-8993-1108b41aedc7.png)
![image](https://user-images.githubusercontent.com/6317240/77243898-20afe700-6c4a-11ea-8ee0-2a2b7d9eb2a3.png)

**Comment by hajimehoshi** [comment]
It looks like beep is using an old Oto version unfortunately. What does `go mod graph` say in your project directory?

**Comment by zx0721** [comment]
go: cannot find main module; see 'go help modules'

**Comment by hajimehoshi** [comment]
Ah ok so you are not using Go modules, right? If so, could you update Oto by `go get -u github.com/hajimehoshi/oto`?

**Comment by zx0721** [comment]
![image](https://user-images.githubusercontent.com/6317240/77510506-ee9cc000-6ea9-11ea-860f-0a8a3fec28ce.png)

**Comment by hajimehoshi** [comment]
So it looked like you have solved the issue by fixing GOOS.

**Comment by Asday** [comment]
It's possible he wants to cross compile, and his issue is that it is broken somehow?

**Comment by zx0721** [comment]
i using "go get -u github.com/hajimehoshi/oto" but error too

**Comment by hajimehoshi** [comment]
So you want to cross-compile? Unfortunately it is impossible due to Cgo. Cgo is not used when GOOS=windows, but is used when e.g., GOOS=linux.

**Comment by hajimehoshi** [comment]
Let me close this. Feel free to reopen if you find other issues.
