### ISSUE TITLE
Not building under linux 386

### ISSUE THREAD

**Issue by skuzzymiglet** [hajimehoshi/oto#113]
I'm compiling my program for my friend who has a 32-bit machine. When I run `go get`, `go build` etc, I get this:

```
$ GOARCH=386 go get

# github.com/hajimehoshi/oto
../../.local/go/pkg/mod/github.com/hajimehoshi/oto@v0.3.1/context.go:63:12: undefined: newDriver
../../.local/go/pkg/mod/github.com/hajimehoshi/oto@v0.3.1/context.go:120:18: undefined: driver
```

**Comment by hajimehoshi** [comment]
Specifying GOARCH explicitly disables CGO. What about specifying `CGO_ENABLED=1`?

**Comment by skuzzymiglet** [comment]
Yes, that solves it, along with installing the 32-bit shared lib for
`libasound` (`multilib/lib32-alsa-lib` on Arch). Thanks, should I add
this to the README/docs?

**Comment by hajimehoshi** [comment]
I'm glad that you have solved the issue!

> should I add this to the README/docs?

I didn't think so as this is a Go's issue. However, at the same time, this is FAQ and kind of a trap for Oto users. I'll accept a PR change if you'd like :-)

If you do, please add a link https://golang.org/cmd/cgo/#hdr-Using_cgo_with_the_go_command and quote this:

> The cgo tool is enabled by default for native builds on systems where it is expected to work. It is disabled by default when cross-compiling. You can control this by setting the CGO_ENABLED environment variable when running the go tool: set it to 1 to enable the use of cgo, and to 0 to disable it.
