### ISSUE TITLE
Sound related error on launch 

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/oto#115]
We received a report that our game crashes when it launches, with the following error:

```
winmm error at waveOutOpen: MMSYSERR_ERROR.
```

OS: Windows10
Graphics Card: GTX1060

Not 100% sure, but this is probably related with the recent switch of the graphics card.
The game was running fine before switching it, it used to be RadeonHD5770.

This looks like a similar issue, possibly this issue is related? 
https://github.com/Try/OpenGothic/issues/38

**Comment by hajimehoshi** [comment]
I think this was solved by rebooting.
