### ISSUE TITLE
Stop writing 0s when there are no players

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/oto#117]
On Android, the current implementation (writing 0s) might affect wake lock values (AudioMix)

CC @wasedaigo

**Comment by WinPooh32** [comment]
I can confirm, that lock happens for linux either, when I try to create 2nd player. 
Issue goes away if I become to feed 1st player by data.

Example 1:
```golang
p1 := otoContext.NewPlayer()
go func(){
   for{    
       // Locked due to no new data.
       p1.Write(...)
   }
}()

p2 := otoContext.NewPlayer() //  Locks here!
```

Example 2:
```golang
p1 := otoContext.NewPlayer()
go func(){
   for{    
       // Not locked, feed player by new data.
       p1.Write(...)
   }
}()

p2 := otoContext.NewPlayer() // No lock here, its fine now.
```

**Comment by hajimehoshi** [comment]
A new audio driver will solve this issue https://github.com/hajimehoshi/oto/issues/134 Stay tuned.

**Comment by hajimehoshi** [comment]
In v2, we should call `(*Context).Suspend` and `(*Context).Resume` for wake locks.
