### ISSUE TITLE
Sample project fails on Manjaro : unable to open slave

### ISSUE THREAD

**Issue by Hultan** [hajimehoshi/oto#125]
I am trying to run the sample code, but it fails on Manjaro Cinnamon with the message below. It fails inside the oto.NewContext() method. I unfortunately do not know enough about sound and drivers etc, to determine if this is a bug or if it is something missing on my machine. Any ideas on how to solve this?

I am using Go 1.15.2, and GoLand 2020.2.3 if that matters.

```
ALSA lib pcm_dmix.c:1090:(snd_pcm_dmix_open) unable to open slave
2020/10/19 14:28:47 oto: ALSA error: No such file or directory
```

**Comment by hajimehoshi** [comment]
I've transferred this issue to Oto.

Hmm, I'm not so familiar with ALSA and I have no idea what todo. Let me investigate.

**Comment by Hultan** [comment]
Thank you, I can unfortunately not help you, because I know even less about ALSA than you. I learned of it today :-)

I hope you find a solution...this looks like a package that I need for my next little project...

**Comment by hajimehoshi** [comment]
Thanks! Do other application using audio work in your environment?

**Comment by Hultan** [comment]
Absolutely, I am watching videos on YouTube and Twitch right now, and playing mp3:s work fine using Clementine. And as I said before, using aplay played a wav file perfectly.

I don't know if this helps but the value of p.handle is nil and the value of cs is 100, when the error occurs.

**Comment by hajimehoshi** [comment]
There are some topics for 'unable to open slave' issue. It looks like this is a FAQ but the solution depends on the environment, so probably I cannot give a straight answer:

* https://classicforum.manjaro.org/index.php?topic=23962.0 (removing and reinstalling pulseaudio?)
* https://dev.to/setevoy/linux-alsa-lib-pcmdmixc1108sndpcmdmixopen-unable-to-open-slave-38on (creating /etc/modprobe.d/default.conf?)
* https://forum.manjaro.org/t/problem-using-alsa-through-go-code/32682/14 (this is yours :-)

Would you try some when you are available?
