### ISSUE TITLE
Brand New APIs: Using io.Reader and using a native mixer instead of internal/mux

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/oto#134]
I sometimes find clicking noises on some platforms especially mobiles and browsers. My understanding is that buffer underflows are happening. Now Oto has its own multiplexer at internal/mux, and I suspect this is the culprit, I'm not 100% sure though. Go's scheduler might not be efficient enough to avoid the underflows. The current multiplexer utilizes io.Pipe and channels. 

So I think we should switch the multiplexer to native ones. Oto will just give data to each audio buffers, and multiplexing will happen internally. This doesn't require Oto's API changes fortunately [1].

As this is a pretty big change, I'll try to implement one by one, starting with the critical ones like mobiles and browsers. Then Oto will have two types of implementations in the migration period.

Any thoughts? @Noofbiz @faiface

CC @sinisterstuf

[1] Though we don't have to change the API in theory, I think we can have a better API set on second thought. See the below comments.

EDIT: a mixer sounds a better word than a multiplexer (Disclaimer: I am not an English native speaker)

**Comment by hajimehoshi** [comment]
Also, probably we have switch from io.Writer to io.Reader to utilize the native APIs. Assuming that native APIs has play/pause controls and volume controls, the new API will be

```
type Context interface {
        NewPlayer() Player
        io.Closer
}

type Player interface {
        io.ReadCloser
        Pause()
        Play()
        Volume() float64
        SetVolume(volume float64)
}
```

As this is a significant breaking change, I don't plan to do that immediately (I think we can use io.Pipe to keep backward compatibility). However, Oto is still v0 so we can add such change in near future.

**Comment by hajimehoshi** [comment]
I'll implement this brand new API in another package like github.com/hajimehoshi/oto/newoto. As it will take long time to support all the platforms, I'll start to do it one by one.

**Comment by sinisterstuf** [comment]
Newoto 🤔 if it would be a second version with a new API a fun play on words could be oto + 2 = *otwo* 😁

**Comment by hajimehoshi** [comment]
Interesting idea 😄 

However, I'll replace the original Oto implementation with newoto in the future, the name here is tentative and not so important :)

**Comment by hajimehoshi** [comment]
Resetting the buffer should be necessary (e.g. when seeking or rewinding the source). Then, the API will be:

```go
type Context interface {
        NewPlayer(io.Reader) Player
        io.Closer
}

type Player interface {
        Pause()
        Play()
        Reset()
        Volume() float64
        SetVolume(volume float64)
        io.Closer
}
```

**Comment by hajimehoshi** [comment]
Interestingly, Linux ALSA doesn't offer a way to play multiple PCM streams from one application.

**Comment by hajimehoshi** [comment]
As there are no objections, I'll start implementing this for browsers first.

**Comment by hajimehoshi** [comment]
As the API can change, I'll implement this in Ebiten, see what's going on, and then port the implementation to this package.

**Comment by hajimehoshi** [comment]
Now I'm implementing the new API's Oto in Ebiten and testing them (https://github.com/hajimehoshi/ebiten/tree/main/audio/internal/readerdriver). After I think this is stable enough, I'll port this to Oto.

I started to think the new API should be v2 rather than v0.x, as the API and the design will be drastically changed. I've not determined yet.

**Comment by hajimehoshi** [comment]
CC @yuikns

The implementation is almost finished and now we are testing. I plan to introduce the new APIs as v2 (then the current version will be v1). Note that v2's context will no longer has `Close`.

**Comment by yuikns** [comment]
> CC @yuikns
> 
> The implementation is almost finished and now we are testing. I plan to introduce the new APIs as v2 (then the current version will be v1). Note that v2's context will no longer has `Close`.

Thank you for your mention. Actually I had already noticed the new API, and trying to use it. I am interested in the macOS, Windows and some embedded machines.

**Comment by hajimehoshi** [comment]
Done!
