### ISSUE TITLE
[QUESTION] Volume adjusting

### ISSUE THREAD

**Issue by kpeu3i** [hajimehoshi/oto#137]
Is it possible to adjust the volume using oto.Player?

**Comment by hajimehoshi** [comment]
Not yet unfortunately (so you have to manipulate the buffers by yourself), but I'm now fixing the implementation and adding a new API to adjust volume.

**Comment by kpeu3i** [comment]
Thank you for your amazing work! looking forward to the new version :) Can you give me suggestions (links, docs, etc) on how to manipulate buffers to adjust volume (as a workaround until the new version is released)?

**Comment by Asday** [comment]
Multiply each sample by a number between 0 and 1.  If you wanna make it sound linear, you'll need to mess around with logarithms:  https://www.dr-lex.be/info-stuff/volumecontrols.html

**Comment by hajimehoshi** [comment]
Converting to float values -> Multiplying the volume -> Converting to bytes back should work.

https://github.com/hajimehoshi/ebiten/blob/master/audio/writerplayer.go#L211-L216

**Comment by kpeu3i** [comment]
@Asday @hajimehoshi  thanks a lot!
