### ISSUE TITLE
How to play a wav file?

### ISSUE THREAD

**Issue by nskforward** [hajimehoshi/oto#141]

**Comment by hajimehoshi** [comment]
You have to parse a wav format by yourself. Oto is not a decoder.

http://soundfile.sapp.org/doc/WaveFormat/

My implementation: https://github.com/hajimehoshi/ebiten/blob/master/audio/wav/decode.go#L107

**Comment by nskforward** [comment]
@hajimehoshi thank you, but not clear yet.
WAV file consist of 2 parts - headers and body. I parsed headers.
I just want to understand how I can push body to the speaker.

**Comment by hajimehoshi** [comment]
As wav's body is a raw format, you can pass it to Oto's players as it is.

**Comment by nskforward** [comment]
@hajimehoshi thank you! The simplest example is working fine:
```
func PlayWAV(filename string) error {
	data, err := ioutil.ReadFile(filename)
	if err != nil {
		return err
	}
	r := bytes.NewReader(data[44:])
	ctx, err := oto.NewContext(16000, 1, 2, 3200)
	if err != nil {
		return err
	}
	p := ctx.NewPlayer()
	if _, err := io.Copy(p, r); err != nil {
		return err
	}
	if err := p.Close(); err != nil {
		return err
	}
	return nil
}
```
