### ISSUE TITLE
Stuttering on Windows10 running example

### ISSUE THREAD

**Issue by tiagolobocastro** [hajimehoshi/oto#142]
Hi, 

I've been having some some sound issues on windows10 on another sound library which makes use of oto: (https://github.com/faiface/beep) so I decided to try oto directly and I seem to hit the same kind of issue just by running the example\main.go. The sound is stuttering.

If I increase the buffer size to 5k, 6k, 7k it starts with a bit of crackling and then plays fine.
If I increase the buffer size to 8k it plays perfectly from the start!

Any ideas on what could be the issue and is there any info I could provide to help?

Thanks!

**Comment by hajimehoshi** [comment]
Now I'm reimplementing Oto completely to reduce stuttering: #134

**Comment by tiagolobocastro** [comment]
Hmm if it tends to happen on mobile and browsers only it's strange if it's the same thing happening on my box, it's a 1yo pc with a 3700x cpu.

**Comment by hajimehoshi** [comment]
I think v2 doesn't cause the noises. Feel free to reopen if you still have an issue with v2. Thanks,
