### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by nboughton** [hajimehoshi/oto#143]
OS: Arch Linux
Go version: 1.16.5

Attempting to play files always results in a stack dump at the end.

Here's my play function:

```
func (e *Episode) Play() error {
	// Get MP3 url
	req, err := http.Get(e.Mp3)
	if err != nil {
		return err
	}
	defer req.Body.Close()

	dec, err := mp3.NewDecoder(req.Body)
	if err != nil {
		return err
	}

	ctx, err := oto.NewContext(dec.SampleRate(), 2, 2, 4096)
	if err != nil {
		return err
	}
	defer ctx.Close()

	plr := ctx.NewPlayer()
	defer plr.Close()

	fmt.Printf("Episode: %s\n", e.Title)
	if _, err := io.Copy(plr, dec); err != nil {
		return err
	}

	// Dont forget to write the store after each succesful play
	e.Played = true
	return nil
}
```
Stack dump attached
[dump.txt](https://github.com/hajimehoshi/oto/files/6626599/dump.txt)

The file plays correctly and panics immediately after. It seems to occur when ctx.Close() is called.

**Comment by hajimehoshi** [comment]
Thanks, I'll take a look

**Comment by hajimehoshi** [comment]
However, the new version I am now implementing will not have a feature to close the context. Then I might leave this as 'won't fix'.

**Comment by hajimehoshi** [comment]
As I commented above, v2 doesn't close a context.
