### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by kpeu3i** [hajimehoshi/oto#152]
There is no way to handle the error that occurred in [driver_unix.go](https://github.com/hajimehoshi/oto/blob/main/driver_unix.go#L84) from the outside (defer/recover won't work in that case because the error is raising from the different goroutine).

My current [workaround](https://github.com/kpeu3i/oto/commit/692c6ec4b19ae41eecfff7e6224f92d967d5ca0e) (I know it's not the best one) implies extracting `c.readAndWrite` goroutine into a separate method `context.Run`. This approach allows me to handle runtime errors in my application logic and restart it properly when the error is raised.

**Comment by hajimehoshi** [comment]
Sure, I'll take a look
