### ISSUE TITLE
Pipewire Compatibility 

### ISSUE THREAD

**Issue by distek** [hajimehoshi/oto#156]
Hi! Thanks for all your work on this.

Is there any chance that pipewire compatibility is in the works?

Currently, when trying to compile this on Fedora 35, I get the following:
```
> PKG_CONFIG_PATH=/usr/lib/pkgconfig go run .
# github.com/hajimehoshi/oto
/bin/ld: skipping incompatible /usr/lib/libasound.so when searching for -lasound
/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/11/../../../libasound.so when searching for -lasound
/bin/ld: skipping incompatible /lib/libasound.so when searching for -lasound
/bin/ld: skipping incompatible /usr/lib/libasound.so when searching for -lasound
/bin/ld: cannot find -lasound
/bin/ld: skipping incompatible /usr/lib/libasound.so when searching for -lasound
/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/11/../../../libasound.so when searching for -lasound
/bin/ld: skipping incompatible /lib/libasound.so when searching for -lasound
/bin/ld: skipping incompatible /usr/lib/libasound.so when searching for -lasound
collect2: error: ld returned 1 exit status
```

I have both `alsa-lib` and `alsa-lib-devel` installed. I had to use that `PKG_CONFIG_PATH` so it could find the `alsa.pc` during the build.

_I'm just assuming this is a pipewire issue_ - If it's not, or if you you need more information, please let me know!

The example code that I'm running is from the beep library:
https://github.com/faiface/beep/tree/master/examples/tone-player

**Comment by hajimehoshi** [comment]
Hi,

I don't know about PipeWire and I don't plan to support this so far. Doesn't your ALSA work with Oto?

**Comment by distek** [comment]
I have other programs that work with alsa without issue (Renoise comes to mind) so I think it might be some weird library incompatibility? I'm not certain. I'll try and play with the Oto source a bit and see if I can figure out what is going on

**Comment by hajimehoshi** [comment]
Thanks. This might be a general issue of Cgo, but I am not sure.

**Comment by distek** [comment]
_Disregard..._

As it turns out, there's two separate packages for the 32bit and 64bit alsa-lib-devel packages:
```
alsa-lib-devel.i686                               1.2.6.1-3.fc35                         @updates
alsa-lib-devel.x86_64                             1.2.6.1-3.fc35                         @updates
```

I only had the 32bit ones installed for whatever reason.


Closing - was 100% my end.
