### ISSUE TITLE
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave

### ISSUE THREAD

**Issue by paij0se** [hajimehoshi/oto#164]
oto: ALSA error: No such file or directory

**Comment by JackMordaunt** [comment]
I've seen similar issues on linux. Using `pipewire-alsa` has alleviated the problem.

**Comment by paij0se** [comment]
I forgot to say that the problem is in on PopOs 22.04

**Comment by hajimehoshi** [comment]
Is this still an issue?
