### ISSUE TITLE
looping playback

### ISSUE THREAD

**Issue by JackMordaunt** [hajimehoshi/oto#165]
Maybe I've missed something obvious, but is there a way to loop playback until stopped with the current API? 

If not, would this functionality be a good fit for oto? 

Either implement looping natively (require manual `Reset` to stop), let the caller know when playback has finished with a channel or callback so they can restart it, or allow the player to play from an infinite source eg an `io.Reader` that implements a circular buffer.

**Comment by hajimehoshi** [comment]
> or allow the player to play from an infinite source eg an io.Reader that implements a circular buffer.

You can play an infinite stream of io.Reader.

**Comment by JackMordaunt** [comment]
Excellent.

I was confused because it looked like the player did it's own buffering, so I was worried about OOM by supplying infinite `io.Reader`.

I must have misread the code, thanks!

**Comment by hajimehoshi** [comment]
The buffer size is finite whatever the source is, so you don't have to worry about OOM.

**Comment by yur4568037** [comment]
Hi hajimehoshi,
Can you help me with infinite stream? In my program I periodically receive byte packages of size 320 byte from UDP. I made io.Reader from buffer 1280 byte, started oto.Play but how to trace the end of the buffer? I use io.Seek when oto.Play reads buffer completely but it happenes after some time and the sound is noisy becose of this.

**Comment by hajimehoshi** [comment]
> how to trace the end of the buffer?

I don't fully understand your question but is the stream infinite or not? What does 'tracing' mean here?

**Comment by yur4568037** [comment]
Sorry, maybe I sad it the wrong, my English is poor. I create usual buffer of size 1280 byte and make io.Reader from it. Buffer isn't infinite of cource. Next I create NewPlayer from oto context with this new io.Reader. Next I cyclicly add new data from UDP to 1280 byte buffer. As I understand I must move pointer of io.Reader when oto.Player reads all the data from io.Reader? How can I make "infinite" io.Reader from not infinited byte buffer?

**Comment by hajimehoshi** [comment]
> How can I make "infinite" io.Reader from not infinited byte buffer?

You can make an infinite stream from [NewInfiniteLoop](https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2/audio#NewInfiniteLoop).

**Comment by hajimehoshi** [comment]
Or you can create your own infinite io.Reader. See `examples/sinewave` for example.

**Comment by yur4568037** [comment]
Thank you very much! I will have learned, it is very useful information.
