### ISSUE TITLE
SetBufferSize is inaccessible using Context.NewPlayer

### ISSUE THREAD

**Issue by lucianthorr** [hajimehoshi/oto#166]
I may be just approaching the implementation wrong but I'm finding that there's no way to set the internal buffer size from outside of the oto package.  Since `player` is a private struct, there's no way to access its `SetBufferSize` or know that it implements `BufferSizeSetter` or set the context's defaultBuffersize.

Is that intentional?  Should I just be implementing my own `Player`?

Thanks!

**Comment by hajimehoshi** [comment]
> Is that intentional? Should I just be implementing my own Player?

Yes, this is intentional for backward compatibility. Please cast your player to the interface type `BufferSizeSetter`.

This is documented at: https://pkg.go.dev/github.com/hajimehoshi/oto/v2#Context.NewPlayer

> The returned player implements both Player and BufferSizeSetter.
