### ISSUE TITLE
test fails with Go 1.16

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/oto#183]
https://github.com/hajimehoshi/oto/runs/7974256368

```
Run go test -tags=example  -v ./...
  go test -tags=example  -v ./...
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
=== RUN   TestEmptyPlayer
--- PASS: TestEmptyPlayer (0.00s)
PASS
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2 pc=0x110fc94]

goroutine 17 [running, locked to thread]:
github.com/ebitengine/purego.callbackWrap(0x2)
	/Users/runner/go/pkg/mod/github.com/ebitengine/purego@v0.0.0-20220823124403-58aa9be54b86/syscall_darwin.go:102 +0x54
FAIL	github.com/hajimehoshi/oto/v2	0.322s
?   	github.com/hajimehoshi/oto/v2/example	[no test files]
?   	github.com/hajimehoshi/oto/v2/internal/mux	[no test files]
?   	github.com/hajimehoshi/oto/v2/internal/oboe	[no test files]
FAIL
Error: Process completed with exit code 1.
```

https://github.com/ebitengine/purego/blob/58aa9be54b86ebaa662778658ecf943a3d1976ac/syscall_darwin.go#L98-L106

Is it possible that `a *callbackArgs` is nil? Could you take a look? @TotallyGamerJet

**Comment by TotallyGamerJet** [comment]
I am not able to reproduce this error. Is there some environment variable that is set?

**Comment by hajimehoshi** [comment]
Nothing special. I just run it on GitHub Actions: https://github.com/hajimehoshi/oto/blob/test/.github/workflows/test.yml

**Comment by TotallyGamerJet** [comment]
I'm not sure how to proceed without being able to reproduce. Does it work on all the versions except 1.16? If so, that'll give at least _some_ place to start looking

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/oto/runs/7987605470

Go 1.17 passed, so I think Go 1.16 is suspicious.

I think just a hack to add a nil check would be fine since this panic happens at the end of the process. Also, assuming this happens only with old Go, just a hacky patch would be enough. What do you think?

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/oto/runs/7987678918 Hmm, all the tests passed this time. The behavior might be flaky. I'll retry Go 1.16

**Comment by hajimehoshi** [comment]
Interestingly, this error is deterministic on a commit https://github.com/hajimehoshi/oto/commit/96206db272075d1ce96162cf2ae314732194ab04, whose parent is https://github.com/hajimehoshi/oto/commit/ab14c2bea787e5cb6eb6817cb5e821a57adf740d: https://github.com/hajimehoshi/oto/actions/runs/2911873757 but on the latest commit (just renaming files!), this error is not reproducieble.

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/oto/runs/7996106085 This error still happens only with Go 1.16 macOS 🤔

**Comment by hajimehoshi** [comment]
> `github.com/ebitengine/purego.callbackWrap(0x2)`

So the value `2` is passed as an address to a callbackArgs object. I was wondering when this happens...

```
	// Create a struct callbackArgs on our stack to be passed as
	// the "frame" to cgocallback and on to callbackWrap.
	// $24 to make enough room for the arguments to runtime.cgocallback
	SUBQ $(24+callbackArgs__size), SP
	MOVQ AX, (24+callbackArgs_index)(SP)  // callback index
	MOVQ R8, (24+callbackArgs_args)(SP)   // address of args vector
	MOVQ $0, (24+callbackArgs_result)(SP) // result
	LEAQ 24(SP), AX                       // take the address of callbackArgs
```

**Comment by hajimehoshi** [comment]
I'm not 100% confident but these might be related:

https://github.com/golang/go/issues/40724
https://go-review.googlesource.com/c/go/+/305669

If supporting Go 1.16 is difficult, what about giving up removing `runtime/cgo` on Go 1.16?

**Comment by hajimehoshi** [comment]
Sorry for spamming, but I could reproduce the issue on my local machiine:

```
$ go1.16.15 test ./... -count=1000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2 pc=0x110fc94]

goroutine 17 [running, locked to thread]:
github.com/ebitengine/purego.callbackWrap(0x2)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.0.0-20220823124403-58aa9be54b86/syscall_darwin.go:102 +0x54
FAIL    github.com/hajimehoshi/oto/v2   0.240s
?       github.com/hajimehoshi/oto/v2/internal/mux      [no test files]
?       github.com/hajimehoshi/oto/v2/internal/oboe     [no test files]
FAIL
```

**Comment by TotallyGamerJet** [comment]
So I think the issue is calling convention. Go 1.16 was the last version to use stack passed calling convention. 1.17 started using registers. Since I've been working with 1.17 and above I wrote the callbackWrapInternal as moving from register to stack but if it's already on the stack which it is on 1.16 it'll put garbage there. This is likely the case since the call to the wrap function happens in [cgocallbackg1](https://github.com/golang/go/blob/6a9c674a09b057a641527ac847cbdf1a3824b753/src/runtime/cgocall.go#L315). And since this is go code it will compile to the internal Abi which on 1.16 is stack NOT registers like I assumed. So it should be enough to add a #define with a different wrapper for 1.16 and below. But I'm not sure how to do that other then a asm_1.16.s and asm_1.17+.s files.

If what I think is the cause truly is then 1.15 should also fail. 

This wouldn't have been an issue if it was possible to use <ABIInternal> flag :( but that's only allowed in the runtime

**Comment by hajimehoshi** [comment]
> But I'm not sure how to do that other then a asm_1.16.s and asm_1.17+.s files.

Me neither. I couldn't find a good macro to determine the Go version.

So we would have to split the necessary part into two files with `go1.17` and `!go1.17` build tags unfortunately.

**Comment by hajimehoshi** [comment]
I'll revert the changes for Oto tomorrow unless purego is fixed until then. After I confirm the purego fix, I'll re-revert the change.

**Comment by hajimehoshi** [comment]
Sure!

**Comment by hajimehoshi** [comment]
I marked this issue 'fixed' in Oto. Let's continue to discuss the purego issue at https://github.com/ebitengine/purego/issues/25
