### ISSUE TITLE
mp3 version support

### ISSUE THREAD

**Issue by wa2nfn** [hajimehoshi/oto#190]
I'm audio clueless, and low on the Go curve as well.

On the Oto v2 page I tried the Playing From Memory example to get my feet wet:

1- it appears an import of bytes is missing
2- I got it an mp3 I had recently got from another app, and got mp3.NewDecoder MPEG version 2.5 not supported.
    Is that to old or new? If I use your pkg to create and the play the MP3 do I need to worry about code getting stale?

**Comment by hajimehoshi** [comment]
> 1- it appears an import of bytes is missing

Fixed.

> 2- I got it an mp3 I had recently got from another app, and got mp3.NewDecoder MPEG version 2.5 not supported.

I think the version 2.5 is not supported.
https://github.com/hajimehoshi/go-mp3/issues/48

**Comment by hajimehoshi** [comment]
This is not a question about Oto. Let me close this.
