### ISSUE TITLE
SEGV on macOS 13

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/oto#195]
```
$ go run ./example/
signal: segmentation fault
```

I tested 1c2dd819a0b88c2a82cee95be51fe74105cff4ab but this happens with older commits.

/CC @TotallyGamerJet

**Comment by hajimehoshi** [comment]
The culprit was 595bc3caefb1f6baf1ea60850a5007cae6770b14, but we cannot revert this unfortunately.

**Comment by hajimehoshi** [comment]
`_AudioQueueEnqueueBuffer` crashed after some calls.

**Comment by hajimehoshi** [comment]
More detialed log is in https://github.com/hajimehoshi/ebiten/issues/2440

**Comment by hajimehoshi** [comment]
Perhaps, isn't there imcompatibility about struct layouts between macOS 12 and macOS 13?

**Comment by TotallyGamerJet** [comment]
Perhaps I'll check each one. It may also be that a variable is not staying alive or being put on the heap.

**Comment by TotallyGamerJet** [comment]
I ran it on arm64 with no crash and switching to amd64 using Rosetta crashes with SIGSEGV

**Comment by TotallyGamerJet** [comment]
I have verified that all 3 structs have the same size as their Cgo counterpart

**Comment by TotallyGamerJet** [comment]
The bug is because _AudioQueueNewOutput's callback `render` appears to crash the system. Changing that to be a Cgo callback fixes the error. I'll submit a PR as a temporary fix but I'll need more time to investigate exactly why the callback fails.

**Comment by hajimehoshi** [comment]
Instead, not calling `_AudioQueueEnqueueBuffer` also stops crashing, but this just suspends calling the callback.
