### ISSUE TITLE
the example from the readme is not easy to compile

### ISSUE THREAD

**Issue by volker-schukai** [hajimehoshi/oto#210]
I came from a program i wanted to test that uses this lib. i wanted to test the example briefly. but got nowhere. I have written here my steps a little together, maybe these are helpful.

I created a go project with the [source from the readme](https://github.com/hajimehoshi/oto#playing-sounds-from-memory)

```bash
$ vim main.go  // source from readme

//  modules
$ go get github.com/hajimehoshi/go-mp3
$ go get github.com/hajimehoshi/oto/v2

// build
$ CGO_ENABLED=1 go build  main.go
.....

```

 and i get the error:

```plain
github.com/hajimehoshi/oto/v2@v2.4.0/driver_unix.go:21:11: fatal error: alsa/asoundlib.h: No such file or directory

 21 | // #include <alsa/asoundlib.h>
      |    
```

environment

```bash
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
.....

$ cat  /usr/include/alsa/asoundlib.h
/**
 * \file include/asoundlib.h
 * \brief Application interface library for the ALSA driver
 *.....

$go version
go version go1.20 linux/amd64


```

with CGO_CFLAGS I get a bit further, but something seems to be missing.

```bash
$ CGO_ENABLED=1 CGO_CFLAGS="-I/usr/include/"   go build -v  main.go
```

```bash
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lgcc_s
```

**Comment by volker-schukai** [comment]
By the way, I don't need a solution for this, because i don't try the program further. i just wanted to document this here. If there is no simple solution, the ticket can simply be closed.

**Comment by Asday** [comment]
It's worth explaining how you installed GCC, and demonstrating that it works when compiling a C hello world example.

**Comment by hajimehoshi** [comment]
> fatal error: alsa/asoundlib.h: No such file or directory

https://github.com/hajimehoshi/oto#linux

Have you installed ALSA?

**Comment by volker-schukai** [comment]
Thank you for your time and response.

gcc --version
gcc (GCC) 12.3.0

```c
#include <stdio.h>

int main() {
    printf("Hello, World!\n");
    return 0;
}
```

gcc hello.c -o hello works 
alsa is installed.
