### ISSUE TITLE
Reusing buffer

### ISSUE THREAD

**Issue by tdewolff** [hajimehoshi/oto#212]
Thanks for this awesome library! I was using `faiface.beep` which seems to be a slight layer over this library, and was causing me huge amounts of memory allocations. Probably due to the difference in sample representation between both, it didn't really reuse buffers which causes a background music on repeat to allocate (and deallocate) about 1GB over the course of 15 minutes.

Well, I thought to get my hand dirty and use this library directly. First, I noticed that the resampling algorithm is about 4 times slower so I'm trying to port that from `beep`, but if I load all my WAVs and do all resampling at the beginning, I'm pretty sure I won't have any heap allocations in my game and can pretty much play without GC interruptions :-D

Anyways, the problem I have is that it seems that audio playback seems to cut off when playing a second or third time (it even may cause a crash: `panic: not reach at /home/taco/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.5/audio/internal/convert/resampling.go:167` which I suppose is due to re-resampling?). I believe this was because the resampling result wasn't really saved, but calculated on the fly? Anyways, that's not the case because I still experience this issue with a simple `bytes.Reader` stream. This is the (pseudo) code that I use:

```go
buf, err := ReadWav(filename)  // buf is a bytes.Reader

ctx, ready, err := oto.NewContext(SampleRate, NumChannels, BitsPerSample/8)
if err != nil {
    log.Printf("WARNING: could not initialize sound: %v", err)
}
<-ready

for i := 0; i < 3; i++ {
    buf.Seek(0, io.SeekStart)  // start at the beginning every time
    player := ctx.NewPlayer(buf)
    player.Play()
    time.Sleep(duration)
}
```

This cause the second or third time to stop prematurely, upon which curiously `player.UnplayedBufferSize() == 0` or at least much lower than otherwise.

The number of read actions on a buffer are as follows: for a sample rate of 11025 it reads in chucks of 22048 (why not 22050?) which for this WAV gets filled entirely for the first read, filled partially for the second read, and returns `0, EOF` for the third read (strangely it usually make an unnecessary fourth read after that!).

When playing with `BufferSize` it seems that for a smaller buffer size than the audio data, it sometimes skips some of the buffered chunks. Only when buffer size is larger than the audio data it seems to work every time. I suspect there is a bug here...! Or maybe I'm doing something wrong?

EDIT: v1 of Oto seems to have a quite natural API, but closing players doesn't unblock `Player.Write` and causes a crash when closing the context!

EDIT2: maybe I figured out the error in reasoning from my side, you shouldn't be creating new Players every time (which I felt was quite unnatural) but I should keep feeding the `io.Reader` it accepts with audio data it should play!

**Comment by hajimehoshi** [comment]
Beep uses Oto v1 and Oto v1 is no longer maintained.

**Comment by hajimehoshi** [comment]
If the same issue happens with v2, please let me know

**Comment by tdewolff** [comment]
Well I figured it out, my fault ;-) Quite a nice API!

Perhaps the documentation could be expanded in saying that you need to make sure that the buffer size of `Context` is smaller than the buffer size for the players.

**Comment by tdewolff** [comment]
@hajimehoshi The issues above were for v2. I tried v1 only briefly. Thanks anyways!

**Comment by hajimehoshi** [comment]
Ok, please provide a minimal code to reproduce the issue, thanks
