### ISSUE TITLE
fyne package android error

### ISSUE THREAD

**Issue by dove0012** [hajimehoshi/oto#249]
PS D:\project\xxxxxx> fyne package -os android -appID com.xxxxxx.www -name "xxxxxx"
go build -buildmode=c-shared -o C:\Users\zhenlin.liu\AppData\Local\Temp\fyne-work-1492359412\lib\armeabi-v7a\libgoxxxxxx.so xxxxxx failed: exit status 1
# github.com/ebitengine/oto/v3/internal/oboe
oboe_aaudio_AudioStreamAAudio_android.cpp:323:56: error: unknown type name 'aaudio_allowed_capture_policy_t'
oboe_aaudio_AudioStreamAAudio_android.cpp:323:89: error: cannot initialize a parameter of type 'int32_t' (aka 'int') with an lvalue of type 'oboe::AllowedCapturePolicy'

**Comment by dove0012** [comment]
`
var (
	//go:embed success.mp3
	music []byte
)

func RepeatPlay(ctx context.Context) {
	// Convert the pure bytes into a reader object that can be used with the mp3 decoder
	fileBytesReader := bytes.NewReader(music)

	// Decode file
	decodedMp3, err := mp3.NewDecoder(fileBytesReader)
	if err != nil {
		panic("mp3.NewDecoder failed: " + err.Error())
	}

	// Prepare an Oto context (this will use your default audio device) that will
	// play all our sounds. Its configuration can't be changed later.
	op := &oto.NewContextOptions{
		SampleRate:   44100,                   // Usually 44100 or 48000. Other values might cause distortions in Oto
		ChannelCount: 2,                       // Number of channels (aka locations) to play sounds from. Either 1 or 2. 1 is mono sound, and 2 is stereo (most speakers are stereo)
		Format:       oto.FormatSignedInt16LE, // Format of the source. go-mp3's format is signed 16bit integers.
	}

	// Remember that you should **not** create more than one context
	otoCtx, readyChan, err := oto.NewContext(op)
	if err != nil {
		panic("oto.NewContext failed: " + err.Error())
	}
	// It might take a bit for the hardware audio devices to be ready, so we wait on the channel.
	<-readyChan

	// Create a new 'player' that will handle our sound. Paused by default.
	player := otoCtx.NewPlayer(decodedMp3)

	defer player.Close()

	// We can wait for the sound to finish playing using something like this
	for {
		select {
		case <-ctx.Done():
			return
		default:
			if !player.IsPlaying() {
				player.Seek(0, io.SeekStart)
				// Play starts playing the sound and returns without waiting for it (Play() is async).
				player.Play()
			}

			for player.IsPlaying() {
				time.Sleep(time.Millisecond)
			}

			time.Sleep(time.Second * 2)
		}
	}
}
`

**Comment by dove0012** [comment]
@hajimehoshi if not use Oto, fyne command is ok

**Comment by hajimehoshi** [comment]
I don't know how the fyne command works. Ask the fyne team.

**Comment by dove0012** [comment]
> I don't know how the fyne command works. Ask the fyne team.

github.com/hajimehoshi/oto/v2 build with fyne is ok

**Comment by hajimehoshi** [comment]
OK, I'm not sure what's going on, but please ask the fyne team.

**Comment by hajimehoshi** [comment]
If you can reproduce the issue without `fyne` command, then I'll start investigation.
