### ISSUE TITLE
how stop playing?

### ISSUE THREAD

**Issue by pvitaliy84** [hajimehoshi/oto#30]
Hello. I can play any music, but i understand how stop it? Maybe, player.stop() ?

**Comment by hajimehoshi** [comment]
Hi,

Just `Close()` should fine.

**Comment by pvitaliy84** [comment]
I can't close before io.Copy(p, d) not ending

**Comment by hajimehoshi** [comment]
It is impossible to suspend `io.Copy`. If you want to do, I'd recommend to pass chunks to the player's `Write` without `io.Copy` with a for loop.

**Comment by pvitaliy84** [comment]
Thank you, you helped me!
