### ISSUE TITLE
Cannot Cross Compile For Linux

### ISSUE THREAD

**Issue by nstehr** [hajimehoshi/oto#34]
Hello

I have been using oto on a project of mine and it has been working great.  I'm now wanting to cross compile the application for linux, built on my mac.  However, I'm getting the following error:
```
./player.go:25:18: undefined: player
```
Building for OSX and cross compiling for windows works fine.
```
Nathans-MacBook-Air:oto nstehr$ go version
go version go1.9.2 darwin/amd64
Nathans-MacBook-Air:oto nstehr$ go build
Nathans-MacBook-Air:oto nstehr$ GOOS=windows go build
Nathans-MacBook-Air:oto nstehr$ GOOS=linux go build
# _/Users/nstehr/oto
./player.go:25:18: undefined: player
```
Version of oto library: `commit 029232d8b473a85bc966df7706341c3592c632a6`

**Comment by hajimehoshi** [comment]
Hi, thank you for using Oto.

Unfortunately, Oto uses cgo for macOS and this prevents Oto from cross-compiling.

**Comment by nstehr** [comment]
Ok thanks for the quick reply
