### ISSUE TITLE
Add prerequisite for alsa/asoundlib.h in README.md

### ISSUE THREAD

**Issue by gongdo** [hajimehoshi/oto#37]
It's quite basic, but there's some Linux idiots just like me ;)
So it would be great if README.md mentions that how to get `alsa/asoundlib.h`.
Like this:

## Prerequisite
- Ubuntu/Debian
```
sudo apt update -y && apt install -y libasound2-dev
```

**Comment by hajimehoshi** [comment]
That makes sense very much :-) I'll add that note later. Thanks!
