### ISSUE TITLE
Propose Logo/Icon

### ISSUE THREAD

**Issue by mirzazulfan** [hajimehoshi/oto#41]
Hi @hajimehoshi .. I'm a graphic designer and an open source enthusiast. I would like to contribute to your project by proposing a logo/icon design for it if you allow me. I'll be doing it as a gift for free to your project.
Best regard.
Mirza Zulfan.

**Comment by hajimehoshi** [comment]
Hi, thank you for your great kindness, but I'd not need logos or icons for this project so far.
