### ISSUE TITLE
linux compile 32-bit error

### ISSUE THREAD

**Issue by alphayan** [hajimehoshi/oto#42]
Hi:
I use `go build` and it's work well.
When I use `GOARCH=386 CGO_ENABLED=1 go build`,It's return an error like this
```

1 errors occurred:
--> linux/386 error: exit status 2
Stderr: # voice/vendor/github.com/hajimehoshi/oto
/usr/bin/ld: 找不到 -lasound
collect2: error: ld returned 1 exit status
```
How can I  solve it?

**Comment by alphayan** [comment]
well ,I download a 32-bit lib,it works well

**Comment by hajimehoshi** [comment]
Right, as oto uses cgo, crossplatform compiling is very limited unfortunately.

**Comment by alphayan** [comment]
That's true ,Thanks for your reply.
