### ISSUE TITLE
oto: waveOutOpen error: MMSYSERR_NOMEM

### ISSUE THREAD

**Issue by jicg** [hajimehoshi/oto#46]
In the windows system, the mp3 file is played every second, and the error is given when the time is long. What could be the cause, how can I solve this problem?
```bash
oto: waveOutOpen error: MMSYSERR_NOMEM
```

**Comment by hajimehoshi** [comment]
Thank you for reporting. The error means that you couldn't allocate memory. How big is the mp3 you are trying to play? Which Window 32bit or 64bit are you using?

**Comment by jicg** [comment]
Which Window 32bit or 64bit：“Window 64bit ”
How big is the mp3：“4k ”

**Comment by hajimehoshi** [comment]
> In the windows system, the mp3 file is played every second

Does this mean you are opening Oto's players every second (without closing)?

**Comment by jicg** [comment]
This is my code  ，I closed.
```golang
const SOUND_SO_REJECT     = "SOUND_SO_REJECT"
var files map[string][]byte = map[string][]byte{}

func main(){
    //Load the mp3 file into the files variable
     ...
     c = cron.New()
    c.AddFunc("@every 1s", func() {
		go func() {
			if err := Play(audio.SOUND_SO_REJECT); err != nil {
				logs.Error(err)
			}
		}()
     })
     c.Run()
}



func Play(filename string) error {
	dec, data, err := minimp3.DecodeFull(files[filename])
	if err != nil {
		return err
	}
	player, err := oto.NewPlayer(dec.SampleRate, dec.Channels, 2, 1024*4)
	if err != nil {
		return err
	}
	defer player.Close()
	player.Write(data)
	return nil
}
```

**Comment by hajimehoshi** [comment]
This might be a threading issue. Let me check later. Thank you!

**Comment by hajimehoshi** [comment]
Excuse me but what is 'cron'?

**Comment by jicg** [comment]
“https://github.com/robfig/cron” Time task package

**Comment by hajimehoshi** [comment]
Now you can create multiple players via `(*Context).NewPlayer`. Please check this out!
