### ISSUE TITLE
Allow only one instance of Player or multiple instances

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/oto#47]
I realized that multiple Player instances might causes problems in the current implementation (e.g. #46). I'm still investigating this, but at least the fact is I've not considered multiple instances.

To solve this problem, there are 2 suggestions:

1. Allow only one Player instance. This is simple, but users would need to mixing if they want to play multiple sources (actually I do this in Ebiten).

2. Allow multiple Player instances. Oto does multiplexing sources.

I'm leaning toward 2. since it wouldn't break existing usages. Any thoughts? CC @faiface @Noofbiz

**Comment by hajimehoshi** [comment]
> Allow multiple Player instances. Oto does multiplexing sources.

I found a problem: `io.Writer`'s `Write` requires that the write must wait until all the given bytes are written. Then, if one of the players (implementing `io.Writer`) blocks, would other players be blocked?

**Comment by Noofbiz** [comment]
I like the idea of 2, since all the multiplexing could then be done in one place rather than across every library that utilizes Oto.

**Comment by hajimehoshi** [comment]
OK. Let's continue to discuss:

There are several ideas to achieve multiple players:

* Allow multiple `NewPlayer` call: This doesn't break the current behavior. The problem is that `NewPlayer` takes the number of channels, the byte size of a sample, and the sample rate. What if the given arguments are contradicted? I think we can adjust e.g. the maximum number of channels, but what about the sample rate?
* Add `(*NewPlayer).NewWriter` returning a new `io.WriteCloser`. I prefer this, but if the player still implements `io.WriteCloser`, the API is a little ugly. Users would be confused since both `Player` and its `Writer` implement `io.WriteCloser`
  * Additionally, we can remove `(*NewPlayer).Write` and `Close`, but this breaks the current API.

**Comment by hajimehoshi** [comment]
My current preference (so far) is

* Add `(*Player).NewWriter` returning `io.WriteCloser`
* Remove `Write` and `Close` from `*Player`. This breaks the current API, but fortunately the version is < 1.0.

**Comment by hajimehoshi** [comment]
Yet another idea:

* Add `type Context struct` and `func NewContext(ch, size, samplerate) *Context`
  * `Context` has a function `NewPlayer` that returns an `io.WriteCloser`
* A `Context` object can be created only once
* The existing `func NewPlayer(ch, size, samplerate)` will be a shorthand of `NewContext(ch, size, samplerate).NewPlayer()`

This doesn't break the existing API. This sounds the best so far?

**Comment by faiface** [comment]
Here's another idea: how about just removing Player altogether and make global functions instead, just like speaker in Beep? That way it's ensured by the API itself that only one instance is ever used and mixing can be done on the user's part.

**Comment by hajimehoshi** [comment]
Hi, thank you for your suggestion!

IMO, I'd want Oto's player to be an `io.Writer` so that various `io` functions are available (e.g. `io.Copy`). That's true that we don't have to care about multiple calls of `NewContext` in yours way, but it would be still possible that we can initialize the state, like sample rate, multiple times.

**Comment by faiface** [comment]
Well, `io.Writer` issue could be solved by having a global `oto.Writer` instance that would call the other functions. There could also be a single `oto.Init` (or some other name) function for setting the sample rate, etc.

Of course, I'll be fine with whatever you eventually implement ;)

**Comment by hajimehoshi** [comment]
> There could also be a single oto.Init (or some other name) function for setting the sample rate, etc.

I thought there is not a big difference between `Context` object way and `oto.Init` way. Both can be called multiple times. Maybe, `oto.Init` might be easier to users to understand that this function must be called only once.

I think your suggestion makes sense. Actually for a singleton, global functions might be better (e.g. `http` or `rand` package's default states).

> Of course, I'll be fine with whatever you eventually implement ;)

Thanks. I'd like to keep the backward compatibility. Let's discuss API improvement later.

**Comment by hajimehoshi** [comment]
Done.

**Comment by medusalix** [comment]
@hajimehoshi What about creating different players with distinct sample rates? The current implementation blocks the creation of a new `Context`, even when the current `Context` is closed. My use case is a music streaming application which accepts audio files with varying sample rates. Before the change, I could just close the current `Player` and open a new one with different parameters.

Would you accept a PR with the following change?

```diff
func (c *Context) Close() error {
+	c.theContext = nil

	if err := c.driverWriter.Close(); err != nil {
		return err
	}
	if err := c.mux.Close(); err != nil {
		return err
	}
	return <-c.errCh
}
```

**Comment by hajimehoshi** [comment]
I'd need to check reusing the driver is possible in every environment, but this sounds make sense. I'll accept this after some tests.
