### ISSUE TITLE
Add doc comments

### ISSUE THREAD

**Issue by faiface** [hajimehoshi/oto#5]
Doc comments are empty now. When I have time, I can take care of that, if someone else doesn't do it sooner.

**Comment by hajimehoshi** [comment]
Sure, please go ahead :-), or I might also do that when I'm available. I think adding doc to `player_openal.go` is necessary and sufficient since Linux uses that.

**Comment by hajimehoshi** [comment]
Now the interface is unified to Player struct in `player.go`.

**Comment by hajimehoshi** [comment]
I'll close this issue. Of course, let's continue to add comments when necessary.
