### ISSUE TITLE
Oto and RPi

### ISSUE THREAD

**Issue by skyritsis** [hajimehoshi/oto#50]
Hello, I was wondering if you had any experience in deploying oto on an rpi. I tried cross compiling the library, without success.

Any insight would be helpful.
thank you for your time.

**Comment by hajimehoshi** [comment]
Hi, thank you for asking a question!

Could you tell me what is RPi?

**Comment by skyritsis** [comment]
I am sorry, I meant raspberry pi. An embedded Linux platform with an arm processor.

**Comment by hajimehoshi** [comment]
As Oto works on Linux, Oto should work on Raspberry Pi. Please check the requirements https://github.com/hajimehoshi/oto#prerequisite :-)

**Comment by skyritsis** [comment]
Thank you for your response and your time.
Cheers.

**Comment by cgxeiji** [comment]
For future reference with cross-compiling for the RPi, you can use the following Docker container:

```
FROM balenalib/raspberry-pi-golang:latest
RUN [ "cross-build-start" ]
RUN apt-get -qq update -y && apt-get install -y libasound2-dev
RUN [ "cross-build-end" ]
```

then `cd` into the `Dockerfile` directory and run:
```
sudo docker build --no-cache -t rpi-audio ./
```

finally, compile with:
```
sudo docker run --rm -ti -v "$HOME/go/src":/go/src rpi-audio /usr/bin/qemu-arm-static /bin/sh -c "cd $(pwd | grep -o 'src.*'); go build -o binary -v"
```
