### ISSUE TITLE
NewContext can be called only once

### ISSUE THREAD

**Issue by AkselsLedins** [hajimehoshi/oto#60]
Hello FYI,

![image](https://user-images.githubusercontent.com/18367406/51612169-354aff00-1f21-11e9-81b1-e1af6de65722.png)

It's may be related to https://github.com/hajimehoshi/oto/commit/345927246826d1522bb3c191a01e93bca91ceabd

And maybe it belongs to : https://github.com/faiface/beep

I don't know I'm not sure

Thanks

**Comment by AkselsLedins** [comment]
https://github.com/HowlSlack/app/blob/master/howl/audio.go#L20


It's a pretty simple app that reads incoming messages from a slack channel and then reads them out loud.
But I use `beep` that internally use your awesome lib.

I should propose to make a `go.mod` file for `faiface/beep` to avoid breaking changes.

@faiface

**Comment by hajimehoshi** [comment]
My guess is that `beep`'s `speaker.Init` must be called only once, thought this is not documented.

**Comment by AkselsLedins** [comment]
Thank you @hajimehoshi for your time.
I really appreciate your work.

**Comment by hajimehoshi** [comment]
Oh have you solved this?

Thank you for compliments!

**Comment by AkselsLedins** [comment]
https://github.com/HowlSlack/app/commit/cfc24b34fbaf208c646747e4f32d37bd97349919

I did what you suggested. The issue is that this way the speaker has a fixed sample rate. Imagine you receive audio from multiple sources with different sample rates: that could not work.

I did a workaround to resample the audio streams:

https://github.com/HowlSlack/app/commit/74253c7a005424920ed23c32fbc5ae28c5b1df0b

Only thing that is mysterious to me is that I ask an audio stream with 22050 sample rate to AWS Polly I need to set the speaker's sample rate to 12000 in order to play the sound correctly. And if I ask an audio stream with a 16000 sample rate I need to set the speaker sample rate to 8000 in order to play it properly.

IMHO, But all of this is more a problem in `my code`, or `aws polly`, or `beep` package  issue than `oto`

**Comment by faiface** [comment]
@AkselsLedins Yeah, resampling is what you're supposed to do when you have different sample rates.

Btw, @hajimehoshi, in Beep, you're supposed to call `Init` once at the beginning, but you're also allowed to call it later to reset the speaker and change configuration, such as sample rate, etc. How would that be achieved now?

**Comment by hajimehoshi** [comment]
> you're also allowed to call it later to reset the speaker and change configuration, such as sample rate, etc. How would that be achieved now?

I don't allow it? Now unfortunately it is impossible to reset the sample rate so far.

**Comment by faiface** [comment]
So, Oto does or does not allow it? It did allow it before, and Beep was using that.

**Comment by hajimehoshi** [comment]
No, Oto doesn't allow it. Even if you could do it, I think you were just lucky...

Of course we can change the specification and fix the implementation (perhaps we wouldn't need any change but at least we need to double-check). However, IMHO, I don't think changing sample-rate is an important feature...
