### ISSUE TITLE
error in cgo part of driver_linux.go while cross compiling the example project for linux on arm64 architecture

### ISSUE THREAD

**Issue by matthiasloehr** [hajimehoshi/oto#61]
Hello together,
i have a problem compiling the project for linux on a arm64 platform.
What i figured out so far:
When you want to cross compile something in go that uses cgo you have to enable the cgo cross compiling, which i did as fallowed: **CGO_ENABLED=1**
Also you have to specify the OS and the architecture, which i did as followed: **GOOS="linux"** **GOARCH="arm64"**
Then you have to pic a cross compiler. I choosed **gcc-aarch64-linux-gnu**. To use this cross compiler you have to install the fallowing packages:
**apt-get install gcc-aarch64-linux-gnu**
**apt-get install cpp-aarch64-linux-gnu**
**apt-get install g++-aarch64-linux-gnu**
to take this compilerfor building, you have to insert this command in the build command:
**CC=aarch64-linux-gnu-gcc**
The final Build command looks like this:
**GOOS="linux" GOARCH="arm64 CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc go build -a -o /home/matthias/go/src/github.com/hajimehoshi/oto/playersound /home/matthias/go/src/github.com/hajimehoshi/oto**

The compilation starts but then i get a error in driver_linux on line 22 this is the Error message:
**/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: cannot find -lasound**

this is strange because i definitely have installed libasound2-dev as well and i can find the needed asound.h in the fallowing paths:
**/usr/include/sound
/usr/src/linux-headers-4.15.0-44/include/sound
/usr/src/linux-headers-4.15.0-45/include/sound
/usr/src/linux-headers-4.15.0-44/include/uapi/sound
/usr/src/linux-headers-4.15.0-45/include/uapi/sound
/usr/src/linux-headers-4.15.0-44/include/uapi/linux
/usr/src/linux-headers-4.15.0-45/include/uapi/linux**

I have no idea at all, what could be the problem here, does anyone have an idea?
PS: The normal compilation (without cross compiler) works without any problem
greetings Matthias

**Comment by hajimehoshi** [comment]
Hi,

I'm not familiar with cross-compiling with Cgo. This might be impossible. What is your host environment?

**Comment by matthiasloehr** [comment]
I'm running the development environment (VS-code) on a 386 with Ubuntu 18.04.1.

**Comment by matthiasloehr** [comment]
I'm also not very familiar with cross compiling, especially not, when cgo is involved, that's why
I also fiddled around with the import command of the asound.h,
i tried to import it with within the c-code instead of importing it with the cgo command, but then i got several double definition errors in the fallowing c-code..

**Comment by hajimehoshi** [comment]
Have you installed 64bit version of libasound-dev?

**Comment by matthiasloehr** [comment]
i think so, but i'm not sure...

libasound2-dev:
  Installiert:           1.1.3-5ubuntu0.2
  Installationskandidat: 1.1.3-5ubuntu0.2
  Versionstabelle:
 *** 1.1.3-5ubuntu0.2 500
        500 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.3-5 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 Packages

**Comment by hajimehoshi** [comment]
This sounds like an Ubuntu issue. `dpkg --add-architecture amd64` might solve this, but I am not sure.

https://wiki.debian.org/Multiarch/HOWTO

**Comment by thinkski** [comment]
The error is from the linker -- it needs to link against a version of `libasound` compiled for your target (i.e. `aarch64` (also known as `arm64`)). Only `libasound` for your host architecture (i.e. `amd64`) is available on your system.
