### ISSUE TITLE
Automatic adjusting buffer size

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/oto#66]
Talked with @faiface .

* Make it possible to pass the default (-1) buffer size.
* If the context accepts the default buffer size, the context tries to adjust buffer size dynamically: if the context detects underrun during playing, it increases the buffer size.
* From my experience, browsers require an appropriate and specific buffer size (e.g. 3200 works but power of 2 doesn't). Adjusting buffer size can consider this.

CC @Noofbiz 

Any thoughts?

**Comment by faiface** [comment]
As I said on Gitter, I think there are two things going on here:

- default buffer size
- automatic adjusting of buffer size

Both could be implemented. A default buffer size is useful when the user doesn't really care about it. Automatically adjusting the buffer size is useful most of the time - even if the user wishes to set the initial buffer size themselves.

**Comment by hajimehoshi** [comment]
v2's NewContext no longer takes a buffer size!
