### ISSUE TITLE
Error compiling the example on windows

### ISSUE THREAD

**Issue by musikdusche** [hajimehoshi/oto#67]
I am still a noob when it comes to golang. Sorry in advance, if this is a stupid mistake. I am working with Windows 7 and go version go1.12 windows/amd64

I tried to work with beep from faiface but i always get the same error (even the example from oto):
```
D:\ (bla bla bla)  \go_workspace\src\github.com\hajimehoshi\oto\example>go build main.go
# github.com/hajimehoshi/oto
..\winmm_windows.go:109:11: undefined: "golang.org/x/sys/windows".Errno
```

**Comment by hajimehoshi** [comment]
Hi,

`Errno` should be defined there https://godoc.org/golang.org/x/sys/windows#Errno

Could you try `go get -u golang.org/x/sys/windows` to update the package?

**Comment by musikdusche** [comment]
Thank you very much! This did the trick.

However:
The oto/example sounds very choppy. The go-mp3 example works fine. 
I'll have a closer look later.
