### ISSUE TITLE
how can I change another mp3 to play

### ISSUE THREAD

**Issue by jzhbiao** [hajimehoshi/oto#74]
`
package main

import (
	"io/ioutil"
	"time"
	"github.com/hajimehoshi/oto"
	"github.com/tosone/minimp3"
	"log"
)

func players() error {
	file, _ := ioutil.ReadFile("assets/mp3/test.mp3")
	dec, data, _ := minimp3.DecodeFull(file)

	player, _ := oto.NewPlayer(dec.SampleRate, dec.Channels, 2, 4000)
	player.Write(data)

	dec.Close()
	player.Close()
	return nil
}

func main() {
	for i := 0; i < 3; i++ {
		if err := players(); err != nil {
			log.Fatal(err)
		}
		time.Sleep(time.Second * 5)
	}
}`

when I run above code it got a error:
panic: oto: NewContext can be called only once

**Comment by jzhbiao** [comment]
how can I solve this error, and I want to chenge another mp3 to play , is seems I cant close NewContext then create a new player

**Comment by jzhbiao** [comment]
my test.mp3 is 2 second

**Comment by jzhbiao** [comment]
my test.mp3 is 2 second

**Comment by jzhbiao** [comment]
why I just play once then got error

**Comment by hajimehoshi** [comment]
> why I just play once then got error

In your code, it looks like `oto.NewPlayer` is called multiple times. As you said, create a context by `oto.NewContext` and then call the context's `NewPlayer` instead.

**Comment by jzhbiao** [comment]
thank you
