### ISSUE TITLE
Remove oto.NewPlayer

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/oto#76]
`oto.NewPlayer` (not `(*otoContext).NewPlayer` exists for backward compatibility, but this is confusing (e.g. `oto.NewPlayer` cannot be called multiple times). I started to think this should be removed.

Any thoughts? @faiface @Noofbiz

**Comment by Asday** [comment]
Possible you could have it keep a reference to the returned player, and return that each time?  That way people can still have an easy way to do things, but it removes a gun pointed at their feet.

**Comment by hajimehoshi** [comment]
Thanks. The problem of returning the singleton player is that we cannot expect what should happen when a different sample rate is given.

**Comment by Asday** [comment]
You're for sure right, please ignore me.  :sweat_smile:

**Comment by faiface** [comment]
If you search GitHub, you find that quite a few people are still using it: https://github.com/search?q=%22oto.NewPlayer%22&type=Code . So I'm not sure if it's a good idea to remove it. But perhaps deprecating it, wait some time until people switch and then remove it?

**Comment by hajimehoshi** [comment]
Ah good point... I think removing this is not feasible until everyone uses Go modules.

**Comment by gdm85** [comment]
I think a first step would be to remove it from the example?

**Comment by hajimehoshi** [comment]
CC @DianeLooney 

This API is problematic since calling oto.NewPlayer multiple times causes an error (NewContext cannot be called multiple times), even though oto allows to call NewContext multiple times as long as the context is closed correctly.

It is hard to use oto.NewPlayer correctly. Then, I'll remove this function, maybe this weekend.

**Comment by hajimehoshi** [comment]
> Ah good point... I think removing this is not feasible until everyone uses Go modules.

It's already one year ago. Everyone should use Go modules :-)
