### ISSUE TITLE
winmm error at waveOutOpen: Errno: 1168

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/oto#77]
This can happen when the machine doesn't have any sound devices

**Comment by hajimehoshi** [comment]
I fixed Windows and OpenAL cases.

Linux (ALSA): It looks like there is no 'no device error'?
Android: Not sure :)

**Comment by hajimehoshi** [comment]
I forgot why this is needed. Probably for a CI?

**Comment by divVerent** [comment]
Just seen this again while trying on a fresh Win7 VM. So seems like this has regressed.
