### ISSUE TITLE
Interruptions in sound if I play two files at the same time on android 6.0

### ISSUE THREAD

**Issue by marinat** [hajimehoshi/oto#82]
If I play files one by one there are no problems. But I need play it together.
On mac os and android 7.0 and higher all ok. But on android < 7.0 it looks like player wheezes. I know library that I use for playback audio based on oto. https://github.com/faiface/beep. 

code Example:

https://gist.github.com/marinat/f1f14b61b8cdb070c0d1be14f06e93bd

Please, tell me, where to look for the problem?

**Comment by Asday** [comment]
What was the problem?  Explaining it may help future users, or help improve documentation in future.

**Comment by hajimehoshi** [comment]
CC @faiface

**Comment by marinat** [comment]
Duplicate https://github.com/faiface/beep/issues/61, sorry
