### ISSUE TITLE
gomobile: no current JVM during `oto.NewContext()` on Android

### ISSUE THREAD

**Issue by eliezedeck** [hajimehoshi/oto#83]
Hi,

I'm trying to test **oto** with an Android application. Actually, a Flutter application that allows me to reuse the Golang code that I already wrote, with the help of `gomobile`.

The same Golang code works without any issues when used with the Qt library (via https://github.com/therecipe/qt), initializes and plays without any issues. So, I know the code is correct, but I think it's not properly getting the JVM context (?).

I already have `Seq.setContext(getApplicationContext());` in my Flutter app's `MainActivity.java -- MainActivity.onCreate()`. But whether I set this or not, I always end-up with a `no current JVM` Golang panic.

```
E/Go      ( 9616): Initializing go playlist.go ...panic: no current JVM
E/Go      ( 9616): goroutine 1 [running]:
E/Go      ( 9616): restricted-media-sharing.init.0()
E/Go      ( 9616): 	/.../package/src/business_logic/playlist.go:34 +0x137
F/libc    ( 9616): Fatal signal 6 (SIGABRT), code -6 in tid 9645 (ple.flutter_app)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
```

Here, the line `playlist.go:34` is really `otoc, err = oto.NewContext(44100, 2, 2, BufferSize)`.

Thanks for the help.

**Comment by hajimehoshi** [comment]
Hi, thank you for testing!

My two cents is that you are creating a context at init function instead of main function or later. gomobile is really special: JVM is not registered at init function, and is registered when main function is executed. Would it be possible to defer create Oto's context?

This is a known issue and I've already reported: https://github.com/golang/go/issues/25255

**Comment by eliezedeck** [comment]
Thanks @hajimehoshi ... `init()` doesn't have JVM context indeed.

I have moved the `otoc, err = oto.NewContext(44100, 2, 2, BufferSize)` call, and it doesn't panic anymore. Unfortunately, for reasons I don't know, it just hangs there, and the whole application doesn't seem to respond anymore. Causing an event to be generated causes a signal 3:

```
I/art     (12657): Thread[3,tid=12664,WaitingInMainSignalCatcherLoop,Thread*=0xb4025c00,peer=0x12c000a0,"Signal Catcher"]: reacting to signal 3
I/art     (12657): Wrote stack traces to '/data/anr/traces.txt'
```

After a while, Android tells me that the app is not responding and whether I want to close it. Sometimes, it would complete the call, but most of the time, it would get stuck there forever.

Getting further, it seems to be hanging at the `NewContext() -> d, err := newDriver(sampleRate, channelNum, bitDepthInBytes, bufferSizeInBytes)` call. What weird is that I have placed some `println()` inside the `newDriver` calls, and none of them prints out (may be STDOUT some buffering, I don't know) and thus, I have no idea where or what is causing the freeze.

Note that I have `Seq.setContext(getApplicationContext());` in Java before the call to `oto.NewContext()`. Without this call, it would complain again about *no current JVM*.

**Comment by eliezedeck** [comment]
Looks like my Java call to `Seq.setContext(getApplicationContext())` is still too early. Moving it to right before the library is going to be used fixed it; that is, inside the

I was using it in `MainActivity -> onCreate`, right after the `GeneratedPluginRegistrant.registerWith(this)`.

@hajimehoshi you have mentioned about a "main function" earlier, how can I use that function?

**Comment by hajimehoshi** [comment]
I'm not sure why you call `Seq.setContext(getApplicationContext())`, but looks like you've solved you issue :)

> you have mentioned about a "main function" earlier, how can I use that function?

Oh that's a good point. I was a little misunderstanding. Actually if you use a shared library (gomobile-bind case), there is no main function. I meant regular functions other than init functions. In a shared library, init functions are called when any (regular) functions are called in the first time, and after that, the regular function is called. Then, initializing the context is available in the regular functions.

**Comment by eliezedeck** [comment]
Alright, I thought I missed something about anything `main()` function. Thanks for the clarification.

Well, I have no idea either. But I think, it's safe to set the JVM the first time you use any of your Gomobile functions. As far as I know, the method channel processing should be single-threaded (or at least if I were to be put in charge of the implementation), so a simple boolean check would suffice.

Any way, I think this issue is resolved. For those coming here having this same problem:

- Don't call `oto.NewContext()` in an `init()` function as you don't have any JVM context at that time
- Call `Seq.setContext(getApplicationContext())` right before you start using your Golang library from Java or you'll have *no current JVM* panic somewhere

Thanks @hajimehoshi
