### ISSUE TITLE
gomobile: AudioFlinger could not create a track, status: -12

### ISSUE THREAD

**Issue by eliezedeck** [hajimehoshi/oto#84]
Hi,

After the JVM issues has been resolved, I have added more libraries (gRPC amongst others). To be able to decouple testing, I'm using gRPC to talk to a Golang app on my desktop, and Flutter as the UI. This works well.

But the issue comes when I package the same Golang library with the help of gomobile. When trying to use the library, I get the following error at the `oto.NewContext(...)` call:

```
E/AudioTrack(23057): AudioFlinger could not create track, status: -12
E/AudioTrack-JNI(23057): Error -12 initializing AudioTrack
E/android.media.AudioTrack(23057): Error code -20 when initializing AudioTrack.
E/Go      (23057): panic: java.lang.IllegalStateException: play() called on uninitialized AudioTrack.
```

Anyone knows why is this, or had a similar experience before?
Thanks.

**Comment by hajimehoshi** [comment]
Hmm, I have no idea, but perhaps there might be a conflict between Oto and Flutter.

**Comment by eliezedeck** [comment]
I have tried the same APK on a simulator with API level 27, and now, the error message is different:

```
D/AudioTrack( 4217): Client defaulted notification
W/AudioTrack( 4217): Use of stream types is deprecated for operations other than volume control
W/AudioTrack( 4217): See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
```

May be helpful?

**Comment by eliezedeck** [comment]
Hmm... I believe it is my mistake. There was _a problem in the Android 5.1 simulator_, I could not figure-out what. I have tested on several real devices and they all play fine with no issues. So, I'll close this now.

**Comment by hajimehoshi** [comment]
Oh OK, this happened only on simulator? Thank you for testing!

**Comment by eliezedeck** [comment]
Yes, only on one simulator. Thank you for the library :)
