### ISSUE TITLE
[Question] Is it possible to make libasound dependency optional for startup on Linux? 

### ISSUE THREAD

**Issue by sqshq** [hajimehoshi/oto#86]
I understand that Oto relies on `libasound` to work. But in my case sound functionality is optional, so I'm ok if it doesn't work when `libasound` is not available.

Unfortunately right now binary tries to load `libasound` dynamically on startup, and fails to start the application at all if it is not presented:
```
error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory
```

Is there a way to somehow prevent the startup failure, ignoring the error?

**Comment by hajimehoshi** [comment]
Hi,

It sounds almost impossible to ignore such error. I think `dlopen` sounds the way to go, but I am not sure this would be portable.

**Comment by sqshq** [comment]
Ok, thank you for the response.
