### ISSUE TITLE
oggloop error for some oggs

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/oto#87]
I experienced to receive an error as the follows with some oggs I have converted from mp3. Is that possible to just keep this as a warning? 
```
audio: oggloop error: audio/se/nya.ogg, oggloop: skipping bytes should be positive: -1
```

**Comment by hajimehoshi** [comment]
This is not an Oto's issue but https://github.com/hajimehoshi/oggloop's issue.
