### ISSUE TITLE
Compilation error for ARM architecture

### ISSUE THREAD

**Issue by andrejtad** [hajimehoshi/oto#88]
```
GOOS=linux GOARCH=arm go build
# github.com/hajimehoshi/oto
../../hajimehoshi/oto/context.go:69:12: undefined: newDriver
```

**Comment by hajimehoshi** [comment]
If you are cross-compiling, you'd need `CGO_ENABLED=1`. As Cgo is required, it'd be hard to cross-compile though.

**Comment by andrejtad** [comment]
```
GOOS=linux GOARCH=arm CGO_ENABLED=1 CC=arm-linux-gnueabi-gcc go build
# github.com/hajimehoshi/oto
/usr/lib/gcc-cross/arm-linux-gnueabi/8/../../../../arm-linux-gnueabi/bin/ld: cannot find -lasound
collect2: error: ld returned 1 exit status
```

**Comment by hajimehoshi** [comment]
If you are using non-Linux machine, you need a Linux environment like Docker or a VM.

**Comment by hajimehoshi** [comment]
Let me close this.

**Comment by lynxaegon** [comment]
I have the same issue on linux.

```
~/dev/go# GOOS=linux GOARCH=arm CGO_ENABLED=1 CC=arm-linux-gnueabi-gcc go build
# github.com/hajimehoshi/oto
/usr/lib/gcc-cross/arm-linux-gnueabi/6/../../../../arm-linux-gnueabi/bin/ld: cannot find -lasound
collect2: error: ld returned 1 exit status

~/dev/go# cat /etc/issue
Debian GNU/Linux 9 \n \l
```

**Comment by hajimehoshi** [comment]
Have you installed dependencies?

https://github.com/hajimehoshi/oto#linux

**Comment by CRACKeH** [comment]
I have the same problem..

Building on macOS

`
FROM golang:latest AS builder

RUN apt-get update && \
    apt-get install -y \
    libasound2-dev

# some kind of code

RUN GOOS=linux GOARCH=arm CGO_ENABLED=1 CC=arm-linux-gnueabi-gcc go build -o main .
`

Output:
`
# app/vendor/github.com/hajimehoshi/oto
/usr/lib/gcc-cross/arm-linux-gnueabi/8/../../../../arm-linux-gnueabi/bin/ld: cannot find -lasound
collect2: error: ld returned 1 exit status

`

What I'm doing wrong?

**Comment by hajimehoshi** [comment]
Unfortunately, generally it is impossible to cross-compile a Go project using Cgo.

**Comment by hajimehoshi** [comment]
I'm not so familiar with Docker, I think I cannot give an appropriate advice. I'm sorry.

Have you checked xgo? https://github.com/karalabe/xgo
