### ISSUE TITLE
While building on Linux (Manjaro for example), I get this error.

### ISSUE THREAD

**Issue by cyliamargatroid** [hajimehoshi/oto#89]
[cylia-margatroid@cylia-manjaro build]$ ./get.sh
# github.com/hajimehoshi/oto
go/src/github.com/hajimehoshi/oto/driver_macos.go:19:10: fatal error: AudioToolbox/AudioToolbox.h: No such file or directory
   19 | // #import <AudioToolbox/AudioToolbox.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by hajimehoshi** [comment]
Thank you for reporting.

https://github.com/hajimehoshi/oto/commit/41d0315085596005e146b93e1e2a6c6693f06cb0 should fix this.
