### ISSUE TITLE
Player doesn't satisfy io.Writer's requirements

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/oto#9]
https://golang.org/pkg/io/#Writer

> Write writes len(p) bytes from p to the underlying data stream. It returns the number of bytes written from p (0 <= n <= len(p)) and any error encountered that caused the write to stop early. Write must return a non-nil error if it returns n < len(p). Write must not modify the slice data, even temporarily.

So `Write` must process all given data at one time as long as errors don't occur. Now `Player`'s `Write` might return without processing all given data.

**Comment by hajimehoshi** [comment]
Fixed, but the inner player still doesn't satisfy io.Writer's requirements.

**Comment by faiface** [comment]
Good catch! I suggest simply introducing an expected (i.e. non-fatal) `ErrFullBuffer` error

```go
var ErrFullBuffer = errors.New("oto: player: full buffer") // or some similar description
```

which would be returned in such cases. The documentation would explain that this error is non-fatal, should be expected, similarly to `io.EOF`.

**Comment by hajimehoshi** [comment]
Now `Player`'s `Write` processes all given data. Do you still think an error for skipping as you suggested?

**Comment by faiface** [comment]
Based on the discussion on Gitter, I've come to conclusion that this new blocking behaviour is correct as it enables using the player with other Go I/O handling functions, such as `io.Copy`.

**Comment by hajimehoshi** [comment]
Sounds good :-)
