### ISSUE TITLE
'AL/al.h' file not found on FreeBSD

### ISSUE THREAD

**Issue by krsanky** [hajimehoshi/oto#90]
I am trying to use github.com/faiface/beep which uses oto.
I am on FreeBSD.
I have openal-soft installed:
pkg info -l openal-soft
...
/usr/local/include/AL/al.h
...

~~~
wise@molly:/disk1/home/wise/data/GO/sound1$ go install ./...
# github.com/hajimehoshi/oto
/home/wise/go/pkg/mod/github.com/hajimehoshi/oto@v0.3.1/driver_openal.go:30:11: fatal error: 'AL/al.h' file not found
 #include <AL/al.h>
          ^~~~~~~~~
1 error generated.
~~~

any ideas?

**Comment by hajimehoshi** [comment]
Hi,

What is the result of this command?

```
 pkg-config openal --cflags
```

**Comment by krsanky** [comment]
Hi I was just about to update..

I installed pkgconf and it worked.

Thanks!
