### ISSUE TITLE
noticeable latency on darwin when using 8-bit mono stream

### ISSUE THREAD

**Issue by philhassey** [hajimehoshi/oto#98]
I noticed when using 
```
oto.NewPlayer(44100, 1, 1, 1024)
```
there was about a 92 ms latency between sounds.

When using 
```
oto.NewPlayer(44100, 2, 2, 4096)
```
there is the expected 23 ms latency between sounds.

I examined `driver_darwin.go` and noticed this constant:
```
const queueBufferSize = 4096
```

It appears this is the lower limit of the buffer size for the darwin driver.  This works fine for 16-bit stereo, as it comes out to 23 ms latency.  However, for 8-bit mono, this comes out to 92 ms latency.  I tried manually changing the `queueBufferSize` to be 1024, and this has the desired behavior when using 8-bit mono.

It would be nice if the darwin driver could adjust its `queueBufferSize` depending on the parameters to allow low latency playback when using 8-bit mono.

**Comment by hajimehoshi** [comment]
Yes, changing the buffer size makes sense. I'll fix this soon.

**Comment by hajimehoshi** [comment]
Could you try master? Thanks!

**Comment by philhassey** [comment]
Works perfect now, thanks!
