### ISSUE TITLE
more than 2 (stereo) channels, more than 16 bitdepth

### ISSUE THREAD

**Issue by bh90210** [hajimehoshi/oto#99]
Hello there, 

first, thank you all (author+contributors) for the awesome work!

For my particular usecase I need more than two audio channels and up to 24bit and 32bit resolution.

This is not a feature request as I would like to work on this myself (and if anything meaningful/shareable comes out maybe PR it). But I was wondering since it seems not so hard work to implement any of these two features why haven't you already done it?
Is there maybe some gotcha? or simply not possible to target as many platforms with up to 32bit resolution?

I am mostly interested in desktop, so only linux, mac and windows, if you have any pointers they would be very welcome :)

**Comment by hajimehoshi** [comment]
Hi,

>  But I was wondering since it seems not so hard work to implement any of these two features why haven't you already done it?

That's because I don't need and there have not been any requests :)

> or simply not possible to target as many platforms with up to 32bit resolution?

AFAIK, Android and iOS supports up to 2 channels.
